### ISSUE TITLE
PGv2 Vesting & Contribution Period Update

### ISSUE THREAD

**Issue by timbeiko** [protocolguild/docs#59] opened 2024-01-24 19:34 UTC
Once the v2 contracts are live, PG aims to scale the amount of funds it distributes to members by 10x+. Two values must be chosen that influence how these funds will be distributed: the default vesting contract's duration, and the contribution period for PG eligibility. 

For the Pilot, these were set at 12 months for vesting & 6 months for eligibility. In the PG membership survey done last year, the vast majority of PG was in favor of extending the vesting period for PGv2. I'd like to propose we extend it to 4 years, and consider extending the eligibility period to 12 months. 

A longer vesting period creates longer term incentives for PG members, provides more credibility when soliciting larger donations, and matches what is standard across the crypto/tech ecosystem. PG's goal is to attract and retain contributors to L1, and if its funds vest rapidly, this becomes harder: by the time someone joins PG, the treasury may be depleted! Similarly, if we are to make larger asks of Ethereum ecosystem donors to ensure the long-term maintenance of the network, we should align our vesting horizon with this. A single network upgrade can often take >12 months to go live! And, lastly, a 4 year vesting period is standard across the technology & crypto industry. PG adopting a similar duration strengthens its framing as an alternative to compensation packages for work outside of L1 R&D. 

For these reason, **I'd like to suggest a 4 year vesting period for the default PGv2 vesting contract**. Note that this does not prevent another vesting contract to be deployed with another duration in case an org wanted a shorter/longer vesting period for their donation.

Alongside this, we should decide whether to keep or extend the 6 month period for eligibility, as this also impact when new contributors can start receiving PG funding. I feel less strongly about a duration here, as I think the focus should be on the quality of the contributions. Personally, I would rather have the option to include someone after 6 months if they are contributing significantly, but see the average be longer than that. That said, having a higher bar (12 months?) helps reduce the potential "spam" of many contributor applications who may or may not be qualified. 

We can make these decisions independently, but a new contributor's experience with PG is impacted by both values.

**Comment by potuz** [comment] 2024-01-30 15:25
I agree with all the points exposed here.

**Comment by tvanepps** [comment] 2024-02-08 16:40
closing this as it was confirmed in member discussions outside of this thread. 

note that this repo has been archived and the content brought into the [membership repo](https://github.com/protocolguild/membership) (may be renamed) since this issue was opened, future discussions/PRs should be directed there

**Closed as completed by tvanepps** 2024-02-08 16:40 UTC
